version: '3'
services:
  nodejs:
    image: 'node:12'
    container_name: proxy__node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=${ENV}
    volumes:
      - ./:/home/node/app
    command: sh -c 'npm i -g yarn && yarn run start'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traffic"
      - "traefik.frontend.rule=Host:${DOMAIN}.${BASE}"
      - "traefik.port=9000"
    networks:
      - traffic
networks:
  traffic:
    external: true
